/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/upload'
    | '/albums/$albumId'
    | '/videos/$videoId'
    | '/albums/'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/upload'
    | '/albums/$albumId'
    | '/videos/$videoId'
    | '/albums'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/upload'
    | '/albums/$albumId'
    | '/videos/$videoId'
    | '/albums/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  UploadRoute: typeof UploadRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  UploadRoute: UploadRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
