/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as SinglesRouteImport } from './routes/singles'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosVideoIdRouteImport } from './routes/videos.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglesRoute = SinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosVideoIdRoute = VideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/singles': typeof SinglesRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/s/$token': typeof STokenRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/singles': typeof SinglesRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/s/$token': typeof STokenRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/my-library': typeof MyLibraryRoute
  '/singles': typeof SinglesRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/s/$token': typeof STokenRoute
  '/videos/$videoId': typeof VideosVideoIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/my-library'
    | '/singles'
    | '/stats'
    | '/upload'
    | '/albums/$albumId'
    | '/s/$token'
    | '/videos/$videoId'
    | '/albums/'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/my-library'
    | '/singles'
    | '/stats'
    | '/upload'
    | '/albums/$albumId'
    | '/s/$token'
    | '/videos/$videoId'
    | '/albums'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/my-library'
    | '/singles'
    | '/stats'
    | '/upload'
    | '/albums/$albumId'
    | '/s/$token'
    | '/videos/$videoId'
    | '/albums/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MyLibraryRoute: typeof MyLibraryRoute
  SinglesRoute: typeof SinglesRoute
  StatsRoute: typeof StatsRoute
  UploadRoute: typeof UploadRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  STokenRoute: typeof STokenRoute
  VideosVideoIdRoute: typeof VideosVideoIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singles': {
      id: '/singles'
      path: '/singles'
      fullPath: '/singles'
      preLoaderRoute: typeof SinglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MyLibraryRoute: MyLibraryRoute,
  SinglesRoute: SinglesRoute,
  StatsRoute: StatsRoute,
  UploadRoute: UploadRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  STokenRoute: STokenRoute,
  VideosVideoIdRoute: VideosVideoIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
